# This Azure Pipeline runs unit and integration tests.
# This pipeline is triggered upon making a PR against the main branch.
# Unit tests are defined under ac_mlops_pipeline/tests
# and are executed on the Azure Pipelines agent.
# The integration test deploys and runs the model_training_job defined in ac_mlops_pipeline/resources/model-workflow-resource.yml
# This integration test is run in the staging workspace, as defined under ac_mlops_pipeline/databricks.yml

trigger:
  branches:
    include:
      - sonava_feature #main
  paths:
    include:
      - clv_mlops_pipeline/*
      - '.azure/devops-pipelines/ac-mlops-pipeline-run-tests.yml'

variables:
  - name: workingDirectory
    value: clv_mlops_pipeline
  - group: ac-mlops-pipeline variable group

parameters:
  - name: environment
    displayName: environmentName
    default: staging
    type: string
  - name: country
    displayName: country
    default: de
    type: string  


jobs:
  - job: UnitTests
    displayName: 'Unit Tests'
    # Trigger unit test upon making a PR against the main branch
    #condition: |
    #  and(
    #    not(eq(variables['Build.Reason'], 'IndividualCI')),
    #    eq(variables['Build.Reason'], 'PullRequest'),
    #    eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/sonava_feature')
    #  )
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8

    - script: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r clv_mlops_pipeline/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pytest --junitxml=test-unit.xml
      displayName: 'Run unit tests with pytest'

  - job: deploy_validate
    displayName: 'Deploy and Validate the bundle'
    # Integration tests will only run upon unit tests successfully passing
    dependsOn: UnitTests
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.230.0/install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Extract Databricks version to test installation
    - script: |
        databricks version
      displayName: 'Get Databricks CLI version'

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle validate -t acda-ml-${{ parameters.environment }}
        databricks bundle deploy -t acda-ml-${{ parameters.environment }}
      workingDirectory: $(workingDirectory)
      displayName: Validate and deploy bundle for test deployment target in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        
  - job: IntegrationTests_repurchase_classifier
    displayName: 'Integration repurchase'
    # Integration tests will only run upon unit tests successfully passing
    dependsOn: deploy_validate
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.230.0/install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Extract Databricks version to test installation
    - script: |
        databricks version
      displayName: 'Get Databricks CLI version'

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle run clv_job_repurchase_${{ parameters.country }} -t acda-ml-${{ parameters.environment }}
      workingDirectory: $(workingDirectory)
      displayName: Run the repurchase classifier pipeline in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        
  - job: IntegrationTests_lifetimevalue_classifier
    displayName: 'Integration lifetime'
    # Integration tests will only run upon unit tests successfully passing
    dependsOn: IntegrationTests_repurchase_classifier
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.230.0/install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Extract Databricks version to test installation
    - script: |
        databricks version
      displayName: 'Get Databricks CLI version'

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle run clv_job_lifetime_${{ parameters.country }} -t acda-ml-${{ parameters.environment }}
      workingDirectory: $(workingDirectory)
      displayName: Validate bundle for test deployment target in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        
